version: '2.1'
services:

  config-service:
    build: config-service
    restart: always
    environment:
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
    ports:
      - 8888:8888

  discovery-service:
    environment:
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      CONFIG_SERVICE_URL: http://config-service:8888
    build: discovery-service
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - 8761:8761

  gateway-service:
    environment:
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      CONFIG_SERVICE_URL: http://config-service:8888
      EUREKA_URL: http://discovery-service:8761
    build: gateway-service
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - 80:4000

  track-suggestion-service:
    environment:
      CONFIG_SERVICE_URL: http://config-service:8888
      EUREKA_URL: http://discovery-service:8761
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      OPEN_WEATHER_APP_ID: ${OPEN_WEATHER_APP_ID}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
    build: track-suggestion-service
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - 8989:8989

  monitoring-service:
    environment:
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      CONFIG_SERVICE_URL: http://config-service:8888
      EUREKA_URL: http://discovery-service:8761
    build: monitoring-service
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - 9000:9000



