server:
  port: 4000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: track-suggestion-service
          uri: lb://track-suggestion-service
          predicates:
            - Path=/suggestions/tracks/**